# Generated by Django 3.1.3 on 2020-11-19 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatnoscTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamochodKategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamochodMarka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamochodSilnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SamochodSkrzynia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypUbezpieczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_polisy', models.CharField(max_length=50)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.typubezpieczenia')),
            ],
        ),
        migrations.CreateModel(
            name='SamochodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.samochodmarka')),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_rejestracyjny', models.CharField(max_length=50)),
                ('kolor', models.CharField(max_length=50, null=True)),
                ('pojemnosc_silnika', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('moc_silnika', models.IntegerField(null=True)),
                ('cena_godzina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cena_dzien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kaucja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('satus_samochodu', models.CharField(choices=[('DO', 'Dostępny'), ('NI', 'Niedostępny'), ('SE', 'Serwisowany')], default='DO', max_length=2)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.samochodkategoria')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.samochodmodel')),
                ('silnik', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.samochodsilnik')),
                ('skrzynia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.samochodskrzynia')),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateTimeField()),
                ('data_do', models.DateTimeField()),
                ('uwagi', models.CharField(max_length=200, null=True)),
                ('satus_rezerwacji', models.CharField(choices=[('WE', 'Werfyfikacja'), ('ZA', 'Zaakceptowana'), ('AN', 'Anulowana'), ('WT', 'W trakcie'), ('ZK', 'Zakończona')], default='WE', max_length=2)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.samochod')),
                ('ubezpieczenie', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.ubezpieczenie')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('wysokosc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='wypozyczalnia.platnosctyp')),
            ],
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(choices=[('FV', 'FAKTURA'), ('RA', 'RACHUNEK'), ('PO', 'POTWIERDZENIE')], default='PO', max_length=2)),
                ('rezerwacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.rezerwacja')),
            ],
        ),
        migrations.CreateModel(
            name='DodatkoweOplaty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=50)),
                ('wysokosc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dokument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.dokument')),
            ],
        ),
    ]
