# Generated by Django 3.1.3 on 2020-11-19 18:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('imie', models.CharField(max_length=50, null=True)),
                ('nazwisko', models.CharField(max_length=50, null=True)),
                ('ulica', models.CharField(max_length=50, null=True)),
                ('miasto', models.CharField(max_length=50, null=True)),
                ('kod_pocztowy', models.CharField(max_length=50, null=True)),
                ('numer_telefonu', models.IntegerField(null=True)),
                ('czy_firma', models.BooleanField(null=True)),
                ('numer_nip', models.IntegerField(null=True)),
                ('nazwa_firmy', models.CharField(max_length=50, null=True)),
                ('rola', models.CharField(choices=[('US', 'Uzytkownik'), ('PR', 'Pracownik'), ('AD', 'Administrator')], default='US', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Użytkownicy',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
